on:
  push:
    branches: master

name: Pkgdown

jobs:
  pkgdown:
    runs-on: macOS-latest
    steps:
      - uses: actions/checkout@master
      - uses: r-lib/actions/setup-r@master
      - uses: r-lib/actions/setup-pandoc@master
      - name: Install dependencies
        run: |
          install.packages("ps")
          install.packages("remotes")
          remotes::install_deps(dependencies = TRUE)
          remotes::install_github("jimhester/pkgdown@github-actions-deploy2")
        shell: Rscript {0}
      - name: Install package
        run: R CMD INSTALL .
      - name: Deploy package
        run: pkgdown:::deploy_to_branch(new_process = FALSE, branch = "gh-pages")
        shell: Rscript {0}

